name: "Build Tool"
permissions:
  contents: write
  discussions: write
on:
  push:
    paths:
      - "build.py"
  pull_request:
  workflow_dispatch:
jobs:
  build:
    needs: [build-win,build-linux]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
      - name: Rename Tool
        run: |
          cd TIK-win-cn
          move ./TIK-win.zip ../TIK-5-${{ github.run_number }}-Chinese-win.zip
          cd ..
          cd TIK-linux-cn
          move ./TIK-linux.zip ../TIK-5-${{ github.run_number }}-Chinese-linux.zip
          cd ..
          cd TIK-win-ru
          move ./TIK-win.zip ../TIK-5-${{ github.run_number }}-Russian-win.zip
          cd ..
          cd TIK-linux-ru
          move ./TIK-linux.zip ../TIK-5-${{ github.run_number }}-Russian-linux.zip
          cd ..
          cd TIK-win-en
          move ./TIK-win.zip ../TIK-5-${{ github.run_number }}-English-win.zip
          cd ..
          cd TIK-linux-en
          move ./TIK-linux.zip ../TIK-5-${{ github.run_number }}-English-linux.zip
          cd ..
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          removeArtifacts: true
          name: "TIK-5.${{ github.run_number }}"
          tag: "CI_BUILD_${{ github.run_number }}"
          body: |
            Build times: ${{ github.run_number }}
            Version: 5
            Note:If u cannot run it in linux,you may need do "chmod a+x ./*"
            Minimum support: Ubuntu 20.04 (64bit),Windows Vista (32bit)

            Русский: https://github.com/randcatcraps/TIK/releases
          artifacts: "*.zip"

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x86'
      # You can test your matrix by printing the current Python version
      - name: Update pip
        run:  python -m pip install -U --force-reinstall pip
      - name: Build tool (Chinese)
        run: |
             python build.py
      - name: Upload Win Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: TIK-win-cn
          path: './TIK-win.zip'
      - name: Build tool (English)
        run: |
          del ./TIK-win.zip
          del ./run.py
          del ./run
          move ./run_english.py ./run.py
          python build.py
      - name: Upload Win Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: TIK-win-en
          path: './TIK-win.zip'
      - name: Build tool (Russian)
        run: |
          del ./TIK-win.zip
          del ./run.py
          del ./run.exe
          move ./run_russian.py ./run.py
          python build.py
      - name: Upload Win Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: TIK-win-ru
          path: './TIK-win.zip'
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
          # Optional - x64 or x86 architecture, defaults to x64
      - name: Install Packages
        run: |
            python3 -m pip install -U --force-reinstall pip
            sudo apt update -y && sudo apt install python3-tk -y
      - name: Build Tool (Chinese)
        run: |
             python3 build.py
      - name: Upload Linux Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: TIK-linux-cn
          path: './TIK-linux.zip'

      - name: Build Tool (English)
        run: |
          ls
          rm -rf TIK-linux.zip
          rm -rf run.py
          rm -rf run
          mv run_english.py run.py
          python3 build.py
      - name: Upload Linux Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: TIK-linux-en
          path: './TIK-linux.zip'

      - name: Build Tool (Russian)
        run: |
          rm -rf TIK-linux.zip
          rm -rf run.py
          rm -rf run
          mv run_russian.py run.py
          python3 build.py
      - name: Upload Linux Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: TIK-linux-ru
          path: './TIK-linux.zip'
